% Ayush Basak
% 19ucc016
[y, fs] = audioread('dove.wav');
f = linspace(-fs, fs, 2000);
y1 = mydft(y,2000);
y2 = fft(y,2000);
z1 = myidft(y,2000);
z2 = ifft(y,2000);
subplot(2,2,1);
stem(f,fftshift(abs(y1)));
ylabel('Magnitude');
xlabel('Frequency');
title('Magnitude plot using mydft()');
subplot(2,2,2);
stem(f,angle(y1));
ylabel('Phase');
xlabel('Frequency');
title('Phase plot using mydft()');
subplot(2,2,3);
stem(f,fftshift(abs(y2)));
ylabel('Magnitude');
xlabel('Frequency');
title ('Magnitude plot using fft()');
subplot(2,2,4);
stem (f,angle(y2));
ylabel('Phase');
xlabel('Frequency');
title('Phase plot using fft()');
sgtitle('Ayush Basak 19UCC016');
figure;
subplot(1,2,1);
stem(f,z1);
ylabel('Magnitude');
xlabel('Frequency');
title('IDPT using myidft()');
subplot(1,2,2);
stem(f,z2);
ylabel('Magnitude');
xlabel('Frequency');
title('IDPT using ifft()');